### ISSUE TITLE
Clearing Cache

### ISSUE THREAD

**Issue by nielsdebruin** [ByteInternet/hypernode-vagrant#19]
I installed a module using modman and made some chanegs to the stylesheet. Problem is that changes just aren't showing up in the magento shop. It seems to load the old version of the file. So I tried it on a different vagrant box here all works as expected. So I assume that the file is being cache somewhere. I have disabled caches a flushed everything, including redis(although I don't think that was being used here) and removed var folder contents. Is there any other caches integrated in this image that I might have forgotten.

**Comment by mvschaik** [comment]
Not that I know of. Magento cache and FPC in redis are the obvious suspects as you mentioned. Did you rule out browser cache?

**Comment by nielsdebruin** [comment]
I did, However I think I fixed it by destroying, deleting and redownloading the box. Still no clue what caused it, mabye something in vritualbox.

**Comment by kozie** [comment]
We are having the exact same issue but it also gives another strange behaviour.

When deleting the biggest part of the file of our stylesheet seems to be returning a part of a PHP file. Otherwise an old version of the file is returned when the necessary changes are done to the file.

I haven't tried out flushing Redis cache so i'll be doing that first and let you know if that did the trick.

**Comment by vdloo** [comment]
@kozie have you tried disabling varnish? https://github.com/ByteInternet/hypernode-vagrant#the-web-pages-dont-change

**Comment by kozie** [comment]
Yes, we did and it didn't solve the issue, unfortunately. I tried cache busting by requesting the css file from the webserver with ?v=4 behind it and it solved the issue once. A hard, cached file is returned afterwards.

**Comment by vdloo** [comment]
Are your requests registering in the logs in ```/var/log/nginx/```? Did flushing the redis cache change anything? My guess is that it's probably caching somewhere in your Magento application. 

You could try ```n98-magerun cache:flush``` , that will flush all the caches in your Magento XML configuration.
